server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    com.banking.core: DEBUG
    org.springframework.test: DEBUG

jwt:
  secret: ${JWT_TEST_SECRET:U2FsdGVkX1+XrCkUhz7gU6SzP4E9dyDq0j6f6vOwA1jP4Xl6H3oc61hZGz7Fx0T7}
  expiration: 3600000  # 1 heure
  header: Authorization
  prefix: 'Bearer '