server:
  port: 8000
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core_banking
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always

jwt:
  secret: ${JWT_SECRET:U2FsdGVkX1+XrCkUhz7gU6SzP4E9dyDq0j6f6vOwA1jP4Xl6H3oc61hZGz7Fx0T7}
  expiration: 86400000  # 24 heures en millisecondes
  header: Authorization
  prefix: 'Bearer '

logging:
  level:
    com.banking.core: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO